name: Python CI
run-name: Matrix example

on:
    push:
        branches:
            - main

jobs:
    build-and-test:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest]
                versions: ['3.9', '3.10', '3.11']

        steps:
        - uses: actions/checkout@v4   

        - name: Setup Python ${{ matrix.versions }}
          uses: actions/setup-python@v4
          with:
            versions: ${{ matrix.versions }}

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        
        - name: Run tests
          run: |
            echo "Running tests....."

        
