name: Publish image to docker hub
run-name: ${{ github.actor }} publish image to docker hub

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to the docker hub
              uses: docker/login-action@v3
              with:
                username: destroyyer
                password: ${{ secrets.DOCKER_HUB_TOKEN }}

            - name: Build and Push
              uses: docker/build-push-action@v5
              with:
                push: true
                tags: |
                  destroyyer/web-sql:latest
                  destroyyer/web-sql:${{ github.sha}}


            

            
